name: Deployment (DEV)

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    name: "Deploy to 'dev' server"
    runs-on: on-prem
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Execute deployment
        uses: ./.github/actions/deployment
        with:
          backend_container: erp_backend_dev
          frontend_container: erp_frontend_dev
          scheduler_container: erp_scheduler_dev
          websocket_container: erp_websocket_dev
          queue_container: erp_queue_default_dev
          queue_long_container: erp_queue_long_dev
          queue_short_container: erp_queue_short_dev
